@baseUrl = http://localhost:3000/api

### test
POST {{baseUrl}}/test

### gen-wallpaper
POST {{baseUrl}}/gen-wallpaper
Content-Type: application/json

{
  "description": "have a party with friends in garden"
}

### get-wallpapers
GET {{baseUrl}}/get-wallpapers